{% set name = "prettier" %}
{% set version = "2.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/prettier/prettier/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8f14e810fb2c92b5ab6581543a1819aabb26aae82cd9c0277d87175edf7648ef

build:
  number: 0

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
    - nodejs  # [not win]
  host:
    - nodejs
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - prettier --version | grep "{{ version }}"  # [not win]
    - prettier --version | findstr "{{ version }}"  # [win]
    - where prettier  # [win]

about:
  home: https://github.com/prettier/prettier
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Prettier is an opinionated code formatter.

extra:
  recipe-maintainers:
    - janjagusch
    - xhochy
