{% set name = "prettier" %}
{% set version = "2.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/prettier/prettier/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7241e4588a8d43c2ef9a66508e136451df67be308b808e73923149a4f16a580a

build:
  number: 0

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
    - nodejs  # [not win]
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - prettier --version | grep "{{ version }}"  # [not win]
    - prettier --version | findstr "{{ version }}"  # [win]
    - where prettier  # [win]

about:
  home: https://github.com/prettier/prettier
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Prettier is an opinionated code formatter.

extra:
  recipe-maintainers:
    - janjagusch
    - xhochy
